In [100]:
# create a datafram with random letter as the value in the column

import pandas as pd
import numpy as np
import random
import string

# create a dataframe with random letters
df = pd.DataFrame(np.random.choice(list(string.ascii_lowercase[0:2]), size=(100, 1)), columns=['letter'])
df




letter
0       b
1       a
2       a
3       b
4       a
..    ...
95      a
96      b
97      b
98      b
99      a

[100 rows x 1 columns]

In [101]:
# Method 1: using a map
df['letter'].map({'a': 0, 'b': 1})

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    1
97    1
98    1
99    0
Name: letter, Length: 100, dtype: int64

In [102]:
# Method 2: using a dictionary
df['letter'].replace({'a': 0, 'b': 1})


0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    1
97    1
98    1
99    0
Name: letter, Length: 100, dtype: int64

In [103]:
# Method 3: using a np.where
np.where(df['letter'] == 'a', 0, 1)

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0])

In [104]:
# Method 4: using a np.select and choices as integers

conditions = [
    df['letter'] == 'a',
    df['letter'] == 'b'
]
choices = [0,1]
np.select(conditions, choices, default=np.nan)


array([1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0.,
       1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.])

In [105]:
# Method 5: using lambda function
df['letter'].apply(lambda x: 0 if x == 'a' else 1)

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    1
97    1
98    1
99    0
Name: letter, Length: 100, dtype: int64

In [106]:
# Method 4: using a np.select and choices as integers

conditions = [
    df['letter'] == 'a',
    df['letter'] == 'b'
]
choices = np.arange(0,2)
print(choices)
np.select(conditions, choices, default=np.nan).astype(int)



[0 1]


array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0])